config/routes.rb
ChartChallenge::Application.routes.draw do

  devise_for :users, path_names:  { sign_in: 'login', sign_out: 'logout'},
                     controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :admins, path_names: { sign_in: 'login', sign_out: 'logout'}

  root to: 'home#index'

  get 'dashboard' => 'dashboard#index', as: :dashboard

  resources :foods
  resources :sleeps
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  private

  def date
    Date.parse(params.fetch(:date, Date.today))
  end

  helper_method :date
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div role="navigation" id="nav">
  <ul>
    <li class="active"><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Dashboard', dashboard_url %></li>
    <li><%= link_to 'Foods', foods_url %></li>
    <li><%= link_to 'Sleep', sleeps_url %></li>
    <li><%= link_to 'Excercise', root_path %></li>
  </ul>
</div>
<div class="row">
  <h3>Dashboard</h3>
</div>

<div class="row">
  <div class="large-4 columns">
    <div class="panel">Widget for Food intake summary</div>
  </div>
  <div class="large-4 columns">
    <div class="panel">Widget for recent recipes</div>
  </div>
  <div class="large-4 columns">
    <div class="panel">Widget for physical exercise</div>
  </div>
</div>

<div class="row">
  <div class="large-4 columns">
    <div class="panel">Widget for Sleep summary</div>
  </div>
  <div class="large-4 columns">
    <div class="panel">Widget for weight</div>
  </div>
  <div class="large-4 columns">
    <div class="panel">Widget for work/life/sleep balance</div>
  </div>
</div>

<!--div class="row">
  <h1>Dashboard</h1>

  <h3 class="subheader">
    <%#= link_to "<<", date: @date.prev_month %>
    <%#= @date.strftime("%B %Y") %>
    <%#= link_to ">>", date: @date.next_month %>
  </h3>
  <%#= calendar @date do |date| %>
    <%#= date.day %>
  <%# end %>
</div-->