config/routes.rb
ChartChallenge::Application.routes.draw do

  devise_for :users, path_names:  { sign_in: 'login', sign_out: 'logout'},
                     controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :admins, path_names: { sign_in: 'login', sign_out: 'logout'}

  root to: 'home#index'

  get 'dashboard' => 'dashboard#index', as: :dashboard

  resources :foods
  resources :sleeps
end

app/models/sleep.rb
class Sleep < ActiveRecord::Base
  # Name of this model is terrible!
  belongs_to :user

  validates_uniqueness_of :sleep_date, scope: :user_id

  scope :grouped_by_date, -> { group_by(&:sleep_date) }
  scope :sleep_months, -> {
    group_by { |sleep| sleep.sleep_date.beginning_of_month.sort { |a, b| a[0] <=> b[0] } }
  }
end

app/controllers/sleeps_controller.rb
class SleepsController < ApplicationController
  before_action :authenticate_user!

  def index
    sleep_date = Date.today
    # Sleep grouped by month in hash
    @sleep_months = @sleeps.group_by { |s| s.sleep_date.beginning_of_month }.sort { |a,b| a[0] <=> b[0] }
    # Sleep grouped for use in calendar helper
    # @todo move to helper method
    sleeps_by_date = sleeps.grouped_by_date
    # Date used in calendar and month range
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @year_range = @sleeps.where(:sleep_date => sleep_date.beginning_of_year..sleep_date.end_of_year)

    # Array of hours slept since recording began
    @total_sleep_months_array = @sleep_months.map { |month, sleep| month.strftime("%b") }

    @current_year_sleep_array = @year_range.map { |year_range| year_range.hours }

    # Do I need total?????
    # @total_sleep_array = @sleeps.map { |sleeps| sleeps.hours }
    # @total_average_sleep_time = median(@total_sleep_array)
    # @current_month_average_sleep_time = median(@current_month_sleep_array)

    respond_to do |format|
      format.html { render action: 'index' }
      format.js
    end
  end

  def new
    @sleep = current_user.sleeps.new
  end

  def edit
    @sleep = current_user.sleeps.find(params[:id])
  end

  def create
    @sleep = current_user.sleeps.new(params[:sleep])
    respond_to do |format|
      if @sleep.save
        format.html { redirect_to sleeps_url, notice: 'Sleep was successfully recorded.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    sleep.attributes = permitted_params
    if sleep.save
      redirect_to sleeps_url, notice: 'Sleep was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    sleep.destroy
    redirect_to sleeps_url
  end

  private

  # whitelisted parameters
  #
  # @return [ActionController::Parameters]
  def permitted_params
    params.require(:sleep).permit(:user_id, :hour, :sleep_date)
  end

  # Memoized current user
  #
  # @return [ActiveRecord::Relation<User>]
  def user
    @user ||= current_user
  end

  # A users sleeps
  #
  # @return [ActiveRecord::Collection<Sleep>]
  def sleeps
    user.sleeps
  end

  # A sleep
  #
  # @return [ActiveRecord::Relation<Sleep>]
  def sleep
    sleeps.find_or_initialize_by(id: params.fetch(:id, nil))
  end

  helper_method :user, :sleeps, :sleep
end

app/helpers/sleeps_helper.rb
module SleepsHelper
end

app/views/sleeps/_form.html.erb
<%= form_for (@sleep), :html => { :class => "custom",
                                  :data => { :validate => 'parsley',
                                             :focus => 'first' }} do |f| %>

  <% if @sleep.errors.any? %>
    <ul>
    <% @sleep.errors.full_messages.each do |msg| %>
      <li class="parsley-large-error"><%= msg %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="row collapse">
    <div class="large-4 columns end">
      <%= f.date_select(:sleep_date) %>
    </div>
  </div>

  <div class="row collapse">
    <div class="large-3 columns end">
      <%= f.text_field :hours, :class => 'required',
                               :data => { :required => true,
                                          :minlength => 1,
                                          :maxlength => 2,
                                          :min => 1,
                                          :max => 31,
                                          :type => 'number',
                                          :trigger => 'keyup' } %>
    </div>
  </div>
  <div class="row collapse">
    <div class="large-4 columns">
      <%= f.submit 'Add Sleep', class: 'button' %>
    </div>
  </div>
<% end %>

app/views/sleeps/edit.html.erb
<h3>Edit Sleep</h3>
<%= render 'form' %>
<%= link_to 'Show', @food %>
<%= link_to 'Back', sleeps_path %>

app/views/sleeps/index.html.erb
<div class="row">
  <div class="large-6 columns">
    <h1>Sleep Totals</h1>
  </div>
  <div class="large-6 columns">
    <%= link_to 'Add Sleep Record', new_sleep_path, class: 'button success' %>
  </div>
</div>
<div class="row">
  <div class="large-5 columns">
    <h3 class="month">
      <%= link_to "<", date: @date.prev_month, class: 'cal-larr' %>
      <%= @date.strftime("%B %Y") %>
      <%= link_to ">", date: @date.next_month, class: 'cal-rarr' %>
    </h3>
    <%= calendar @date do |date| %>
      <%= date.day %>
      <% if @sleeps_by_date[date] %>
        <% @sleeps_by_date[date].each do |sleep| %>
          <%= content_tag :span, " ", :data => { :tooltip => "" }, class: 'has-tip overlay', title: "#{sleep.hours} hours of sleep for the #{sleep.sleep_date.day.ordinalize}" %>
        <% end %>
      <% end %>
    <% end %>


    <%# @sleeps.each do |sleep| %>

        <!--h3><%#= sleep.sleep_date.strftime("%B %e %Y") %></h3>
        <h5><%#= sleep.hours %> hours of sleep</h5!-->
    <%# end %>
  </div>
  <div class="large-7 columns">
    <canvas id="sleepChart" width="500" height="415"></canvas>
  </div>
</div>
<div class="row panel">
  <div class="large-5 columns">
  <% @sleep_months.each do |month, sleep| %>
    <ul class="inline-list">
      <h5><%= month.strftime("%B") %></h5>
    <% for sleeps in sleep %>
      <li><%= sleeps.sleep_date.strftime("%B #{sleeps.sleep_date.day.ordinalize}") %></li>
      <li><%= sleeps.hours %> Hours</li>
    <% end %>
    </ul>
  <% end %>
  </div>
</div>

<%= javascript sleeps_path %>

app/views/sleeps/index.js.erb
var sleepChartData = {
  labels : <%= @total_sleep_months_array.to_json.html_safe %>,
  datasets : [
    {
      fillColor : "rgba(226,91,35,.5)",
      strokeColor : "rgba(245,143,79,1)",
      pointColor : "rgba(245,143,79,1)",
      pointStrokeColor : "rgba(245,143,79,1)",
      data : [<% @sleep_months.each do |month, sleep| %>
                <% for s in sleep %>
                  <%= s.hours %>,
                <% end %>
              <% end %>

      ]
    }
  ]
}

var sleepChart = document.getElementById("sleepChart").getContext("2d");

var avgSleep = new Chart(sleepChart).Line(sleepChartData);

app/views/sleeps/new.html.erb
<div class="row">
  <h3>Add Sleep</h3>
  <%= render 'form' %>
  <%= link_to 'Back', sleeps_path %>
</div>