config/routes.rb
ChartChallenge::Application.routes.draw do

  devise_for :users, path_names:  { sign_in: 'login', sign_out: 'logout'},
                     controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :admins, path_names: { sign_in: 'login', sign_out: 'logout'}

  root to: 'home#index'

  get 'dashboard' => 'dashboard#index', as: :dashboard

  resources :foods
  resources :sleeps
end

app/models/food.rb
class Food < ActiveRecord::Base
  include PgSearch

  default_scope { order(name: :asc) }

  pg_search_scope :search, against: [:name, :category],
                           using: { tsearch: { dictionary: "english" } },
                           ignoring: :accents

  def self.text_search(query)
    return all unless query.present?
    rank = <<-RANK
      ts_rank(to_tsvector(name), plainto_tsquery(#{sanitize(query)})) +
      ts_rank(to_tsvector(category), plainto_tsquery(#{sanitize(query)}))
    RANK
    where("to_tsvector('english', name) @@ plainto_tsquery(:q) or to_tsvector('english', category) @@ plainto_tsquery(:q)", q: query).order("#{rank} desc")
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    food.update_attributes(permitted_params)

    if food.save
      redirect_to food, notice: "You've added a new food!"
    else
      render action: 'new'
    end
  end

  def update
    food.update_attributes(permitted_params)

    if food.save
      redirect_to food, notice: "You've updated a food!"
    else
      render action: 'new'
    end
  end

  def destroy
    name = food.name.titleize
    food.destroy
    notice = "#{name} has been removed from foods list"
    redirect_to foods_url, notice: notice
  end

  private

  def permitted_params
    params.require(:food).permit(
      :name,
      :calories,
      :category,
      :cholesterol,
      :commitment,
      :fiber,
      :protein,
      :ratio_carb,
      :ratio_fat,
      :ratio_protein,
      :saturated_fat,
      :serving,
      :sodium,
      :sugar,
      :total_carbohydrate,
      :total_fat
    )
  end

  def foods
    Food.text_search(params.fetch(:query, '')).order(sort_column + " " + sort_direction).paginate(per_page: 10, page: params.fetch(:page, 1))
  end

  def food
    Food.find_or_initialize_by(id: params.fetch(:id, nil))
  end

  def sort_column
    Food.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  helper_method :food,
                :foods,
                :sort_column,
                :sort_direction
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_foods.html.erb
  <table>
    <thead>
      <tr>
        <th width="150"><%= sortable 'name' %> <span class="asc"></span></th>
        <th width="150"><%= sortable 'category' %></th>
        <th width="150"><%= sortable 'commitment' %></th>
        <th width="150"><%= sortable 'serving' %></th>
        <th width="150"><%= sortable 'calories' %></th>
        <th width="150"><%= sortable 'total_fat' %></th>
        <th width="150"><%= sortable 'protein' %></th>
      </tr>
    </thead>
    <tbody>
      <% foods.each do |food| %>
      <tr>
        <td><%= link_to food.name.capitalize, food_path(food) %></td>
        <td><%= food.category.capitalize.pluralize %></td>
        <td><%= food.commitment %></td>
        <td><%= food.serving %></td>
        <td><%= food.calories %></td>
        <td><%= food.total_fat %></td>
        <td><%= food.protein %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate foods %>

app/views/foods/_show_chart.html.erb
  <div class="large-5 columns">
    <div class="panel">
      <h3>Caloric Ratio</h3>
      <canvas id="foodChart" width="300" height="300"></canvas>
      <hr>
      <div class="row">
        <div class="large-6 large-offset-4 columns">
          <span class="small subheader"><%= @food.ratio_fat %>% of calories from fats</span>
        </div>
        <div class="large-2 columns">
          <div class="key fat"></div>
        </div>
        <div class="large-6 large-offset-4 columns">
          <span class="small subheader">
            <%= @food.ratio_protein %>% of calories from protein
          </span>
        </div>
        <div class="large-2 columns">
          <div class="key protein"></div>
        </div>
        <div class="large-6 large-offset-4 columns">
          <span class="small subheader">
            <%= @food.ratio_carb %>% of calories from carbs
          </span>
        </div>
        <div class="large-2 columns">
          <div class="key carb"></div>
        </div>
      </div>
    </div>
  </div>

app/views/foods/_show_recipes.html.erb
  <div class="large-7 columns">
    <ul class="pricing-table">
      <li class="title"><%= @food.name.capitalize %> Recipes</li>
      <li class="description">Recipe description goes here</li>
      <li class="bullet-item">Direction #1</li>
      <li class="bullet-item">Direction #2</li>
      <li class="bullet-item">Direction #3</li>
      <li class="cta-button">
        <%= link_to 'Tweet', food_path(@food), class: 'button radius' %>
        <%= link_to 'Print', food_path(@food), class: 'button radius' %>
        <%= link_to 'Email', food_path(@food), class: 'button radius' %>
      </li>
    </ul>
  </div>

app/views/foods/_show_table.html.erb
  <table>
    <thead>
      <tr>
        <th>Food Category</th>
        <th>Commitment Level</th>
        <th>Serving Size</th>
        <th>Calories</th>
        <th>Total Fat</th>
        <th>Saturated Fat</th>
        <th>Cholesterol</th>
        <th>Sodium</th>
        <th>Total Carbohydrates</th>
        <th>Fiber</th>
        <th>Sugar</th>
        <th>Protein</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @food.category.capitalize %></td>
        <td><%= @food.commitment %></td>
        <td><%= @food.serving %> (g)</td>
        <td><%= @food.calories %></td>
        <td><%= @food.total_fat %></td>
        <td><%= @food.saturated_fat %></td>
        <td><%= @food.cholesterol %></td>
        <td><%= @food.sodium %></td>
        <td><%= @food.total_carbohydrate %></td>
        <td><%= @food.fiber %></td>
        <td><%= @food.sugar %></td>
        <td><%= @food.protein %></td>
      </tr>
    </tbody>
  </table>

app/views/foods/index.html.erb
<div class="row">
  <h1>Food List</h1>
  <%= form_tag foods_path, method: :get, :id => "foods_search" do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <div class="small-10 large-6 columns end">
      <div class="row collapse">
        <div class="small-8 columns">
          <%= text_field_tag :query, params[:query] %>
        </div>
        <div class="small-4 columns">
          <%= submit_tag "Search", name: nil, class: "button prefix" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="row">
  <div id="foods"><%= render 'foods/foods' %></div>
</div>

<%= javascript 'foods' %>

app/views/foods/index.js.erb
$('#foods').html('<%= escape_javascript(render('foods')).html_safe %>');

app/views/foods/show.html.erb
<div class="row">
  <div class="large-6 columns">
    <h3><%= @food.name.capitalize %></h1>
    <h4 class="subheader">Nutrition Information</h3>
  </div>
  <div class="large-4 large-offset-2 columns">
    <%= link_to "Back to food list", foods_path, class: 'button success' %>
  </div>
</div>
<div class="row">
  <%= render 'foods/show_table' %>
</div>

<div class="row">
  <%= render 'foods/show_chart' %>
  <%= render 'foods/show_recipes' %>
</div>

<%= javascript food_path(@food.id) %>

app/views/foods/show.js.erb
var calorieRatioData = [
  {
    label: 'Protein',
    value: <%= @food.ratio_protein %>,
    color:"#F27620"
  },
  {
    label: 'Fat',
    value : <%= @food.ratio_fat %>,
    color : "#DE5200"
  },
  {
    label: 'Carb',
    value : <%= @food.ratio_carb %>,
    color : "#39393B"
  }
]

var foodChart = document.getElementById("foodChart").getContext("2d");

var calorioRatio = new Chart(foodChart).Pie(calorieRatioData);